#pragma once
#include <torch/all.h>
//torch::Tensor gemm_a8w8(
void gemm_a8w8(
    torch::Tensor& XQ,
    torch::Tensor& WQ,
    torch::Tensor& x_scale,
    torch::Tensor& w_scale,
    torch::Tensor& Y);
